# Generated by Django 3.1.1 on 2020-09-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
