# Generated by Django 3.1.1 on 2020-09-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_auto_20200910_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyto',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
